version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${NOTES_DB}
      - WEBUI_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${WEBUI_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL}
      - OPENAI_CHAT_MODEL=${OPENAI_CHAT_MODEL}
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - NOTES_DB=${NOTES_DB}
      - WEBUI_DB=${WEBUI_DB}
    volumes:
      - notes_app_db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - ENABLE_OLLAMA_API=False
      - ENABLE_OPENAI_API=True
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_EMBEDDING_ENGINE=openai
      - RAG_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL}
      - DEFAULT_MODELS=${OPENAI_CHAT_MODEL}
      - ENABLE_EVALUATION_ARENA_MODELS=False
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${WEBUI_DB}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - WEBUI_JWT_SECRET=${WEBUI_JWT_SECRET}
      - WEBUI_JWT_EXPIRES_IN=7d
      - WEBUI_DATABASE_TYPE=postgres
      - WEBUI_DATABASE_HOST=db
      - WEBUI_DATABASE_PORT=5432
      - WEBUI_DATABASE_USER=${POSTGRES_USER}
      - WEBUI_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - WEBUI_DATABASE_NAME=${WEBUI_DB}
    depends_on:
      db:
        condition: service_healthy

volumes:
  notes_app_db_data: 